name: CI
on:
  # - pull_request
  - push

jobs:
  Test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-13 # x86
          - macos-14 # arm64
        d:
          - "ldc-latest"
        node:
          - 20
        pnpm:
          - 9
        compiler:
          - llvm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      # Cache
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.dub
            ~/AppData/Local/dub
            ~/.pnpm-store
            D:\.pnpm-store
            ./.dub
            ~/llvm
          key: "cache-OS:${{ matrix.os }}-D:${{ matrix.d }}-CXX:${{ matrix.compiler }}-${{ hashFiles('./dub.selections.json', './pnpm-lock.yaml')}} }}"
          restore-keys: |
            "cache-OS:${{ matrix.os }}-D:${{ matrix.d }}-CXX:${{ matrix.compiler }}-"

      # Setup compilers and tools
      - name: Setup Cpp
        if: ${{ !contains(matrix.os, 'macos') }}
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true

      - name: Setup Cpp
        if: ${{ contains(matrix.os, 'macos') }}
        uses: aminya/setup-cpp@v1
        with:
          cmake: true
          ninja: true

      - name: Setup D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.d }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}

      # Build and Test

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build.node

      - name: Inspect Despacer
        if: always()
        shell: bash
        run: ls ./despacer/build

      - name: Test
        run: pnpm test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
